"""Checkpoint writer tests (WA1 B5) — including the crash-simulation
that guarantees the atomic-rename pattern actually survives mid-write
interruption.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from planner_state.checkpoint import (
    STATE_FILENAME,
    StateCorruptionError,
    StateStore,
)
from planner_state.schema import (
    Decision,
    LoopState,
    PlannerState,
    Project,
    SCHEMA_VERSION,
    SchemaVersionMismatch,
)


def _seed_state() -> PlannerState:
    return PlannerState(
        schema_version=SCHEMA_VERSION,
        project=Project(name="LD", current_pointer="seed pointer"),
        loop_state=LoopState(current_pass="WA1", current_pass_status="in_progress"),
        decisions=[],
        working_context_digest="initial",
    )


# ---------------------------------------------------------------------------
# Round-trip via disk
# ---------------------------------------------------------------------------

def test_write_then_load_round_trips(tmp_path: Path):
    store = StateStore(tmp_path)
    s = _seed_state()
    store.write(s)
    assert store.exists()
    loaded = store.load()
    assert loaded.to_dict() == s.to_dict()


def test_load_or_init_creates_when_absent(tmp_path: Path):
    store = StateStore(tmp_path / "fresh")
    s = store.load_or_init(project_name="Fresh Project")
    assert s.project.name == "Fresh Project"
    assert store.exists()


def test_load_or_init_returns_existing_when_present(tmp_path: Path):
    store = StateStore(tmp_path)
    store.write(_seed_state())
    s = store.load_or_init(project_name="Different Name Should Be Ignored")
    assert s.project.name == "LD"  # the existing project name wins


def test_load_raises_filenotfound_when_no_state(tmp_path: Path):
    store = StateStore(tmp_path / "empty")
    with pytest.raises(FileNotFoundError):
        store.load()


# ---------------------------------------------------------------------------
# Mutation helpers
# ---------------------------------------------------------------------------

def test_update_loop_state_patches_named_fields(tmp_path: Path):
    store = StateStore(tmp_path)
    store.write(_seed_state())
    store.update_loop_state(
        current_pass="WA2 — Spike",
        current_pass_status="dispatched",
        pending=["A", "B"],
    )
    loaded = store.load()
    assert loaded.loop_state.current_pass == "WA2 — Spike"
    assert loaded.loop_state.current_pass_status == "dispatched"
    assert loaded.loop_state.pending == ["A", "B"]
    # Other fields untouched.
    assert loaded.project.name == "LD"


def test_update_loop_state_rejects_unknown_field(tmp_path: Path):
    store = StateStore(tmp_path)
    store.write(_seed_state())
    with pytest.raises(TypeError, match="unknown field"):
        store.update_loop_state(nonexistent_field=True)


def test_append_decision_appends_in_order(tmp_path: Path):
    store = StateStore(tmp_path)
    store.write(_seed_state())
    store.append_decision(topic="T1", decision="D1", rationale="R1")
    store.append_decision(topic="T2", decision="D2")
    loaded = store.load()
    assert [d.topic for d in loaded.decisions] == ["T1", "T2"]
    assert loaded.decisions[0].rationale == "R1"
    assert loaded.decisions[1].rationale == ""
    # Each decision got an autogenerated ISO date.
    assert loaded.decisions[0].date.endswith("Z")


def test_append_decision_honors_explicit_date(tmp_path: Path):
    store = StateStore(tmp_path)
    store.write(_seed_state())
    store.append_decision(
        topic="T", decision="D", date="2099-01-01T00:00:00Z",
    )
    loaded = store.load()
    assert loaded.decisions[0].date == "2099-01-01T00:00:00Z"


def test_snapshot_is_deep_copy(tmp_path: Path):
    store = StateStore(tmp_path)
    store.write(_seed_state())
    snap = store.snapshot()
    snap.loop_state.pending.append("mutation should not land")
    # Reload from disk — the mutation didn't escape into the file.
    fresh = store.load()
    assert fresh.loop_state.pending == []


def test_update_patches_top_level_fields(tmp_path: Path):
    store = StateStore(tmp_path)
    store.write(_seed_state())
    new_proj = Project(name="LD-renamed", current_pointer="post-update")
    store.update(project=new_proj, working_context_digest="updated")
    loaded = store.load()
    assert loaded.project.name == "LD-renamed"
    assert loaded.project.current_pointer == "post-update"
    assert loaded.working_context_digest == "updated"
    # loop_state untouched.
    assert loaded.loop_state.current_pass == "WA1"


# ---------------------------------------------------------------------------
# Corruption + version handling
# ---------------------------------------------------------------------------

def test_load_raises_corruption_on_invalid_json(tmp_path: Path):
    store = StateStore(tmp_path)
    # Write garbage directly to the canonical path.
    store.state_dir.mkdir(parents=True, exist_ok=True)
    store.state_path.write_text("not json {{{", encoding="utf-8")
    with pytest.raises(StateCorruptionError, match="not valid JSON"):
        store.load()


def test_load_raises_corruption_on_missing_schema_version(tmp_path: Path):
    store = StateStore(tmp_path)
    store.state_dir.mkdir(parents=True, exist_ok=True)
    store.state_path.write_text('{"project": {"name": "X"}}', encoding="utf-8")
    with pytest.raises(StateCorruptionError, match="schema validation"):
        store.load()


def test_load_propagates_schema_version_mismatch(tmp_path: Path):
    """The version mismatch is its own subclass of ValueError that callers
    can catch to drive a migration. checkpoint.py re-raises it without
    wrapping in StateCorruptionError so the caller can distinguish
    "you need to migrate" from "the file is broken."
    """
    store = StateStore(tmp_path)
    store.state_dir.mkdir(parents=True, exist_ok=True)
    payload = {"schema_version": SCHEMA_VERSION + 1, "project": {"name": "X"}}
    store.state_path.write_text(json.dumps(payload), encoding="utf-8")
    with pytest.raises(SchemaVersionMismatch):
        store.load()


# ---------------------------------------------------------------------------
# Atomicity (the load-bearing test)
# ---------------------------------------------------------------------------

def test_atomic_write_survives_simulated_mid_write_crash(
    tmp_path: Path, monkeypatch
):
    """Simulate the writer crashing AFTER the temp file is written but
    BEFORE the os.replace swap. The prior good state must survive
    unchanged; the partial temp file must not be visible as the
    canonical state.

    Implementation: write a known-good state first, then monkey-patch
    ``os.replace`` to raise mid-call. Attempt a write that mutates a
    field. Assert the on-disk canonical file is STILL the prior good
    one, and the load doesn't see partial data.
    """
    store = StateStore(tmp_path)
    good = _seed_state()
    store.write(good)
    canonical_path = store.state_path
    good_text = canonical_path.read_text(encoding="utf-8")

    mutated = _seed_state()
    mutated.project.current_pointer = "MUTATED — this write will be crashed"

    # Sabotage os.replace. The writer should propagate the exception
    # and clean up any orphan temp.
    original_replace = os.replace

    def _crashing_replace(src, dst):  # type: ignore[no-untyped-def]
        raise RuntimeError("simulated crash between fsync and rename")

    monkeypatch.setattr(os, "replace", _crashing_replace)

    with pytest.raises(RuntimeError, match="simulated crash"):
        store.write(mutated)

    # Restore os.replace so we can read state again.
    monkeypatch.setattr(os, "replace", original_replace)

    # The canonical file is unchanged.
    after_text = canonical_path.read_text(encoding="utf-8")
    assert after_text == good_text, (
        "Canonical state file was modified despite the simulated crash. "
        "The writer must not write directly to the canonical path; the "
        "atomic-rename pattern is broken."
    )
    # A loader sees the prior good state.
    loaded = store.load()
    assert loaded.project.current_pointer == good.project.current_pointer
    # The orphan temp file may or may not exist (depends on which point
    # we crashed at); the writer's exception path tries to clean it. The
    # KEY invariant the test pins is the canonical file being unchanged.


def test_orphan_temp_listed_when_cleanup_fails(tmp_path: Path, monkeypatch):
    """If the writer's cleanup itself fails (e.g., a stat race), the
    orphan temp file is left in place but the canonical state is
    still correct + readable. ``list_orphan_temps`` finds it.
    """
    store = StateStore(tmp_path)
    store.write(_seed_state())

    # Manually drop an orphan temp file in the state dir.
    orphan = store.state_dir / ".planner_state.OOPS.json.tmp"
    orphan.write_text("{}", encoding="utf-8")

    found = store.list_orphan_temps()
    assert orphan in found
    # The canonical state still loads cleanly.
    loaded = store.load()
    assert loaded.project.name == "LD"


def test_temp_files_are_cleaned_on_normal_write(tmp_path: Path):
    """After a successful write there are zero orphan temp files in
    the state dir — the temp file became the canonical file via
    os.replace.
    """
    store = StateStore(tmp_path)
    store.write(_seed_state())
    store.write(_seed_state())  # second write, just to be sure
    assert store.list_orphan_temps() == []
    # And the canonical file is the only .json in the dir.
    json_files = [p for p in store.state_dir.iterdir() if p.suffix == ".json"]
    assert len(json_files) == 1
    assert json_files[0].name == STATE_FILENAME
