"""Phase 6: add voting_method, num_winners, tie_resolution to proposals; add proposal_options table; add ballot to votes

Revision ID: 3b89f18aceda
Revises: d909c6da9b8c
Create Date: 2026-04-22 09:31:46.293263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b89f18aceda'
down_revision: Union[str, None] = 'd909c6da9b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('proposal_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_options_proposal_id'), ['proposal_id'], unique=False)

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voting_method', sa.String(), nullable=False, server_default='binary'))
        batch_op.add_column(sa.Column('num_winners', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('tie_resolution', sa.JSON(), nullable=True))

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ballot', sa.JSON(), nullable=True))
        batch_op.alter_column('vote_value',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('vote_value',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.drop_column('ballot')

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_column('tie_resolution')
        batch_op.drop_column('num_winners')
        batch_op.drop_column('voting_method')

    with op.batch_alter_table('proposal_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_options_proposal_id'))

    op.drop_table('proposal_options')
    # ### end Alembic commands ###
