"""add_delegation_intents

Revision ID: 7f4e8c4f07c9
Revises: ef697ad0c0da
Create Date: 2026-04-15 10:30:27.156868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4e8c4f07c9'
down_revision: Union[str, None] = 'ef697ad0c0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegation_intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('delegator_id', sa.String(), nullable=False),
    sa.Column('delegate_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('chain_behavior', sa.Enum('accept_sub', 'revert_direct', 'abstain', name='chain_behavior'), nullable=False),
    sa.Column('follow_request_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'activated', 'expired', 'cancelled', name='delegation_intent_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follow_request_id'], ['follow_requests.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delegator_id', 'delegate_id', 'topic_id', name='uq_delegation_intent')
    )
    with op.batch_alter_table('delegation_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delegation_intents_delegate_id'), ['delegate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_intents_delegator_id'), ['delegator_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delegation_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegation_intents_delegator_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_intents_delegate_id'))

    op.drop_table('delegation_intents')
    # ### end Alembic commands ###
