"""phase4c_organizations_and_multitenancy

Revision ID: d909c6da9b8c
Revises: 3835b0e1b4e4
Create Date: 2026-04-15 20:24:23.531608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd909c6da9b8c'
down_revision: Union[str, None] = '3835b0e1b4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('join_policy', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=False)

    op.create_table('org_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_org_membership_user_org')
    )
    with op.batch_alter_table('org_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('delegate_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delegate_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delegate_applications_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegate_applications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('delegate_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_delegate_profiles_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_delegate_profiles_org_id', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_proposals_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_proposals_org_id', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_topics_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_topics_org_id', 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_topics_org_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_topics_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_proposals_org_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_proposals_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('delegate_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_delegate_profiles_org_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_delegate_profiles_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('delegate_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegate_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_delegate_applications_org_id'))

    op.drop_table('delegate_applications')
    with op.batch_alter_table('org_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_org_memberships_org_id'))

    op.drop_table('org_memberships')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_org_id'))

    op.drop_table('invitations')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
