"""phase3a_delegation_permissions

Revision ID: ef697ad0c0da
Revises: a23af9c11dcb
Create Date: 2026-04-14 11:29:57.415782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef697ad0c0da'
down_revision: Union[str, None] = 'a23af9c11dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegate_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_delegate_profile_user_topic')
    )
    with op.batch_alter_table('delegate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delegate_profiles_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegate_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('follow_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('follower_id', sa.String(), nullable=False),
    sa.Column('followed_id', sa.String(), nullable=False),
    sa.Column('permission_level', sa.Enum('view_only', 'delegation_allowed', name='follow_permission_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follow_relationship')
    )
    with op.batch_alter_table('follow_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_relationships_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_relationships_follower_id'), ['follower_id'], unique=False)

    op.create_table('follow_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='follow_request_status'), nullable=False),
    sa.Column('permission_level', sa.Enum('view_only', 'delegation_allowed', name='follow_permission_level'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'target_id', name='uq_follow_request_requester_target')
    )
    with op.batch_alter_table('follow_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_requests_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_follow_policy', sa.Enum('require_approval', 'auto_approve_view', 'auto_approve_delegate', name='default_follow_policy'), nullable=False, server_default='require_approval'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_follow_policy')

    with op.batch_alter_table('follow_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_requests_target_id'))
        batch_op.drop_index(batch_op.f('ix_follow_requests_requester_id'))

    op.drop_table('follow_requests')
    with op.batch_alter_table('follow_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_relationships_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follow_relationships_followed_id'))

    op.drop_table('follow_relationships')
    with op.batch_alter_table('delegate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegate_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_delegate_profiles_topic_id'))

    op.drop_table('delegate_profiles')
    # ### end Alembic commands ###
